<?php

namespace App\Contracts\Subscription;

use App\Models\Tenant\CorporationInvoice;
use App\Models\Tenant\CorporationSubscription;
use App\Models\Tenant\VenueInvoice;
use App\Models\Tenant\VenueSubscription;

interface PaymentGatewayContract
{
    /**
     * Create or update a customer in the gateway.
     *
     * @return string The gateway customer identifier.
     */
    public function createCustomer(array $data): string;

    /**
     * Tokenize a credit card and return a safe token.
     *
     * $cardData holds the raw card fields (number, holder_name, expiration_month,
     * expiration_year, ccv) plus whatever the gateway needs to identify the
     * cardholder (holder_document, holder_email, holder_postal_code,
     * holder_address_number, holder_phone) and the request origin (remote_ip).
     *
     * @return array{gateway_token: string, brand: string, last4: string}
     */
    public function saveCard(string $customerId, array $cardData): array;

    /**
     * Create a recurring subscription in the gateway for a corporation/venue subscription.
     *
     * $data holds: gateway_customer_id, billing_type (credit_card|pix|boleto),
     * value, next_due_date (Y-m-d), cycle (monthly), gateway_token (when the card
     * was already tokenized) and description.
     *
     * @return array{gateway_subscription_id: string, status: string, next_due_date: string, payload: array<string, mixed>}
     */
    public function createSubscription(CorporationSubscription|VenueSubscription $subscription, array $data): array;

    /**
     * Update the value of a single pending charge generated by a subscription,
     * before it is paid/confirmed (used to reflect variable billing per cycle).
     */
    public function updatePaymentValue(string $gatewayPaymentId, float $newValue): void;

    /**
     * Update the credit card used by a subscription without charging it immediately.
     *
     * @return array{gateway_token: string, brand: string, last4: string}
     */
    public function updateSubscriptionCard(string $gatewaySubscriptionId, array $cardData): array;

    /**
     * Cancel a recurring subscription in the gateway.
     */
    public function cancelSubscription(string $gatewaySubscriptionId): void;

    /**
     * Charge an invoice using the provided payment data.
     *
     * @return array{status: string, gateway_payment_id: string, message: string, payload: array<string, mixed>}
     */
    public function chargeInvoice(VenueInvoice|CorporationInvoice $invoice, array $paymentData): array;

    /**
     * Generate PIX payload for an invoice.
     *
     * @return array{status: string, gateway_payment_id: string, qr_code: string, qr_code_image: string|null, expires_at: string, message: string, payload: array<string, mixed>}
     */
    public function processPix(VenueInvoice|CorporationInvoice $invoice): array;

    /**
     * Generate boleto payload for an invoice.
     *
     * @return array{status: string, gateway_payment_id: string, boleto_url: string, barcode: string, due_date: string, message: string, payload: array<string, mixed>}
     */
    public function processBoleto(VenueInvoice|CorporationInvoice $invoice): array;

    /**
     * Handle an incoming webhook payload.
     *
     * @return array{gateway_payment_id: string, status: string, invoice_type: string, invoice_id: string, amount: float, gateway_subscription_id: ?string, due_date: ?string, payload: array<string, mixed>}
     */
    public function handleWebhook(string $gateway, array $payload): array;
}
